// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Home from "./Home.js";
import * as Curry from "../node_modules/rescript/lib/es6/curry.js";
import * as React from "react";
import * as Jargon from "./Jargon.js";
import * as Firebase from "./Firebase.js";
import * as Reactfire from "reactfire";
import * as Caml_option from "../node_modules/rescript/lib/es6/caml_option.js";
import * as Auth from "firebase/auth";
import * as AppCheck from "firebase/app-check";
import * as Firestore from "firebase/firestore";
import * as RescriptReactRouter from "../node_modules/@rescript/react/src/RescriptReactRouter.js";

function App(Props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var app = Reactfire.useFirebaseApp();
  var auth = Auth.getAuth(app);
  ((self.FIREBASE_APPCHECK_DEBUG_TOKEN = true));
  var appCheck = AppCheck.initializeAppCheck(app, {
        provider: new AppCheck.ReCaptchaV3Provider(Firebase.appCheckToken),
        isTokenAutoRefreshEnabled: true
      });
  var match = React.useState(function () {
        
      });
  var setFirestore = match[1];
  var firestore = match[0];
  React.useEffect((function () {
          var firestore = Firestore.getFirestore(app);
          var __x = Firestore.enableMultiTabIndexedDbPersistence(firestore);
          __x.then(function (param) {
                Curry._1(setFirestore, (function (param) {
                        return Caml_option.some(firestore);
                      }));
                return Promise.resolve(undefined);
              });
          Curry._1(setFirestore, (function (param) {
                  return Caml_option.some(firestore);
                }));
          
        }), []);
  if (firestore === undefined) {
    return "loading...";
  }
  var match$1 = url.path;
  var tmp;
  tmp = match$1 ? (
      match$1.hd === "jargon" && !match$1.tl ? React.createElement(Reactfire.FirestoreProvider, {
              sdk: Caml_option.valFromOption(firestore),
              children: React.createElement(Jargon.make, {})
            }) : "404"
    ) : React.createElement(Home.make, {});
  return React.createElement(Reactfire.AppCheckProvider, {
              sdk: appCheck,
              children: React.createElement(Reactfire.AuthProvider, {
                    sdk: auth,
                    children: tmp
                  })
            });
}

var make = App;

export {
  make ,
  
}
/* Home Not a pure module */
