// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_exn from "../node_modules/rescript/lib/es6/js_exn.js";
import * as Js_json from "../node_modules/rescript/lib/es6/js_json.js";
import * as Belt_Array from "../node_modules/rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "../node_modules/rescript/lib/es6/belt_Option.js";
import * as Caml_js_exceptions from "../node_modules/rescript/lib/es6/caml_js_exceptions.js";

function retrieveOriginalID(id) {
  try {
    var decoded = Js_json.decodeArray(JSON.parse(atob(id)));
    if (decoded !== undefined) {
      return Belt_Option.map(Belt_Option.flatMap(Belt_Array.get(decoded, 3), Js_json.decodeNumber), (function (x) {
                    return x | 0;
                  }));
    } else {
      return ;
    }
  }
  catch (raw_exn){
    var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
    if (exn.RE_EXN_ID === Js_exn.$$Error) {
      console.error("Error decoding ID: " + id);
      return ;
    }
    throw exn;
  }
}

export {
  retrieveOriginalID ,
}
/* No side effect */
