// Generated by ReScript, PLEASE EDIT WITH CARE

import * as FirebaseConfig from "./firebaseConfig";

var firebaseConfig = FirebaseConfig.firebaseConfig;

var FirebaseAppProvider = {};

var FirestoreProvider = {};

var AuthProvider = {};

export {
  firebaseConfig ,
  FirebaseAppProvider ,
  FirestoreProvider ,
  AuthProvider ,
  
}
/* firebaseConfig Not a pure module */
