// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function FooterContainer(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("div", {
                      children: props.children,
                      className: "flex-grow"
                    }),
                JsxRuntime.jsxs("footer", {
                      children: [
                        JsxRuntime.jsx("a", {
                              children: JsxRuntime.jsx("img", {
                                    className: "object-contain h-10",
                                    alt: "KIISE",
                                    src: "/kiise.png"
                                  }),
                              href: "https://kiise.or.kr",
                              rel: "noreferrer noopener",
                              target: "_blank"
                            }),
                        JsxRuntime.jsx("p", {
                              children: "한국정보과학회 쉬운전문용어 제정위원회 지원을 받았습니다.",
                              className: "align-middle"
                            })
                      ],
                      className: "footer bg-base-300 text-base-content p-4 gap-1 items-center"
                    })
              ],
              className: "flex flex-col min-h-screen"
            });
}

var make = FooterContainer;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
