// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function HideUs(props) {
  return JsxRuntime.jsx("div", {
              children: props.children,
              className: "absolute -top-full -left-full"
            });
}

var make = HideUs;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
