// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Home(Props) {
  return React.createElement("h1", undefined, "Hello world, this is EKO!");
}

var make = Home;

export {
  make ,
  
}
/* react Not a pure module */
