// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Home(Props) {
  return React.createElement("div", undefined, React.createElement("h1", undefined, "Hello world, this is EKO!"), React.createElement("a", {
                  href: "/jargon"
                }, "사전 열기"));
}

var make = Home;

export {
  make ,
  
}
/* react Not a pure module */
