// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JargonList from "./JargonList.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as Solid from "@heroicons/react/24/solid";

function Home$SearchBar(props) {
  return JsxRuntime.jsx("form", {
              children: JsxRuntime.jsx("div", {
                    children: JsxRuntime.jsx("input", {
                          className: "input input-bordered w-full rounded-lg",
                          placeholder: "정규식: syntax$",
                          type: "search",
                          value: props.query,
                          onChange: props.onChange
                        }),
                    className: "relative"
                  })
            });
}

var SearchBar = {
  make: Home$SearchBar
};

function Home(props) {
  var match = React.useState(function () {
        return "";
      });
  var setQuery = match[1];
  var query = match[0];
  var match$1 = React.useState(function () {
        return [
                /* English */0,
                "asc"
              ];
      });
  var setOrder = match$1[1];
  var order = match$1[0];
  var onChange = function ($$event) {
    var value = $$event.currentTarget.value;
    setQuery(function (param) {
          return value;
        });
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("div", {
                              children: JsxRuntime.jsx(Home$SearchBar, {
                                    query: query,
                                    onChange: onChange
                                  }),
                              className: "flex-auto"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsxs("label", {
                                      children: [
                                        order[1] === "asc" ? JsxRuntime.jsx(Solid.ArrowUpIcon, {
                                                className: "-ml-2 mr-1 h-5 w-5 text-teal-200 hover:text-teal-100"
                                              }) : JsxRuntime.jsx(Solid.ArrowDownIcon, {
                                                className: "-ml-2 mr-1 h-5 w-5 text-teal-200 hover:text-teal-100"
                                              }),
                                        order[0] ? "한영" : "영한",
                                        JsxRuntime.jsx(Solid.ChevronDownIcon, {
                                              className: "ml-2 -mr-1 h-5 w-5"
                                            })
                                      ],
                                      className: "btn",
                                      tabIndex: 0
                                    }),
                                JsxRuntime.jsxs("ul", {
                                      children: [
                                        JsxRuntime.jsx("li", {
                                              children: JsxRuntime.jsxs("button", {
                                                    children: [
                                                      "한영",
                                                      order[0] ? (
                                                          order[1] === "asc" ? JsxRuntime.jsx(Solid.ArrowUpIcon, {
                                                                  className: "-ml-2 mr-1 h-5 w-5 text-teal-200 hover:text-teal-100"
                                                                }) : JsxRuntime.jsx(Solid.ArrowDownIcon, {
                                                                  className: "-ml-2 mr-1 h-5 w-5 text-teal-200 hover:text-teal-100"
                                                                })
                                                        ) : null
                                                    ],
                                                    onClick: (function (param) {
                                                        setOrder(function (order) {
                                                              if (order[0] && order[1] === "asc") {
                                                                return [
                                                                        /* Korean */1,
                                                                        "desc"
                                                                      ];
                                                              } else {
                                                                return [
                                                                        /* Korean */1,
                                                                        "asc"
                                                                      ];
                                                              }
                                                            });
                                                      })
                                                  })
                                            }),
                                        JsxRuntime.jsx("li", {
                                              children: JsxRuntime.jsxs("button", {
                                                    children: [
                                                      "영한",
                                                      order[0] ? null : (
                                                          order[1] === "asc" ? JsxRuntime.jsx(Solid.ArrowUpIcon, {
                                                                  className: "-ml-2 mr-1 h-5 w-5 text-teal-200 hover:text-teal-100"
                                                                }) : JsxRuntime.jsx(Solid.ArrowDownIcon, {
                                                                  className: "-ml-2 mr-1 h-5 w-5 text-teal-200 hover:text-teal-100"
                                                                })
                                                        )
                                                    ],
                                                    onClick: (function (param) {
                                                        setOrder(function (order) {
                                                              if (order[0] || order[1] !== "asc") {
                                                                return [
                                                                        /* English */0,
                                                                        "asc"
                                                                      ];
                                                              } else {
                                                                return [
                                                                        /* English */0,
                                                                        "desc"
                                                                      ];
                                                              }
                                                            });
                                                      })
                                                  })
                                            })
                                      ],
                                      className: "menu dropdown-content p-2 shadow bg-base-100 rounded-box w-52 mt-4",
                                      tabIndex: 0
                                    })
                              ],
                              className: "dropdown dropdown-end"
                            })
                      ],
                      className: "flex items-center space-x-2"
                    }),
                JsxRuntime.jsx(JargonList.make, {
                      order: order,
                      query: query
                    })
              ],
              className: "grid gap-4 p-5"
            });
}

var make = Home;

export {
  SearchBar ,
  make ,
}
/* react Not a pure module */
