// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function useDebounce(value, delay) {
  var match = React.useState(function () {
        return value;
      });
  var setDebouncedValue = match[1];
  React.useEffect((function () {
          var handler = setTimeout((function () {
                  setDebouncedValue(function (param) {
                        return value;
                      });
                }), delay);
          return (function () {
                    clearTimeout(handler);
                  });
        }), [
        value,
        delay
      ]);
  return match[0];
}

function useClosingDropdown(id) {
  var close = function (dropdown) {
    if (dropdown.hasAttribute("open")) {
      dropdown.removeAttribute("open");
      return ;
    }
    
  };
  var closeDropdown = function () {
    var dropdown = document.getElementById(id);
    if (!(dropdown == null)) {
      return close(dropdown);
    }
    
  };
  React.useEffect((function () {
          var dropdown = document.getElementById(id);
          if (!(dropdown == null)) {
            document.addEventListener("click", (function ($$event) {
                    if (!dropdown.contains($$event.target)) {
                      return close(dropdown);
                    }
                    
                  }));
            window.addEventListener("scroll", (function (param) {
                    close(dropdown);
                  }), {
                  capture: false,
                  once: false,
                  passive: true
                });
          }
          
        }), []);
  return closeDropdown;
}

export {
  useDebounce ,
  useClosingDropdown ,
}
/* react Not a pure module */
