// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.js";
import * as Firebase from "./Firebase.js";
import * as Reactfire from "reactfire";
import * as PervasivesU from "../node_modules/rescript/lib/es6/pervasivesU.js";
import * as Client from "react-dom/client";
import * as JsxRuntime from "react/jsx-runtime";

import './main.css'
;

var rootElement = document.querySelector("#root");

if (rootElement == null) {
  PervasivesU.failwith("DOM root is missing");
} else {
  var root = Client.createRoot(rootElement);
  root.render(JsxRuntime.jsx(Reactfire.FirebaseAppProvider, {
            firebaseConfig: Firebase.firebaseConfig,
            children: JsxRuntime.jsx(App.make, {})
          }));
}

export {
  
}
/*  Not a pure module */
