// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Loader from "./Loader.js";
import * as Belt_List from "../node_modules/rescript/lib/es6/belt_List.js";
import * as Reactfire from "reactfire";
import * as Belt_Array from "../node_modules/rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "../node_modules/rescript/lib/es6/belt_Option.js";
import * as Belt_HashMapString from "../node_modules/rescript/lib/es6/belt_HashMapString.js";
import * as Firestore from "firebase/firestore";

function constructForest(comments) {
  var roots = {
    contents: /* [] */0
  };
  var commentNodeTable = Belt_HashMapString.make(10);
  Belt_Array.forEach(comments, (function (comment) {
          var node = {
            comment: comment,
            parent: undefined,
            children: /* [] */0
          };
          Belt_HashMapString.set(commentNodeTable, comment.id, node);
          if (comment.parent === "") {
            roots.contents = Belt_List.add(roots.contents, node);
            return ;
          }
          
        }));
  Belt_HashMapString.forEach(commentNodeTable, (function (param, node) {
          var parent = node.comment.parent;
          if (parent === "") {
            return ;
          }
          var parentNode = Belt_Option.getExn(Belt_HashMapString.get(commentNodeTable, parent));
          parentNode.children = Belt_List.add(parentNode.children, node);
          node.parent = parentNode;
        }));
  return [
          roots,
          commentNodeTable
        ];
}

function makeComment(param) {
  var match = param.comment;
  var children = param.children;
  return React.createElement("div", {
              key: match.id
            }, React.createElement("div", {
                  className: "grid grid-cols-2"
                }, React.createElement("div", undefined, match.user), React.createElement("div", undefined, match.timestamp.toDate().toDateString()), React.createElement("div", undefined, match.comment)), React.createElement("div", {
                  className: "ml-4"
                }, makeSiblings(children)));
}

function makeSiblings(siblings) {
  return React.createElement("div", undefined, Belt_Array.map(Belt_List.toArray(siblings), makeComment));
}

function Jargon$CommentInput(Props) {
  return React.createElement("form", undefined, React.createElement("div", {
                  className: "p-2 gap-3 grid grid-cols-1 place-items-end"
                }, React.createElement("textarea", {
                      className: "h-24 p-1 border place-self-stretch",
                      id: "comment",
                      name: "comment",
                      placeholder: "여러분의 생각은 어떠신가요?"
                    }), React.createElement("input", {
                      className: "px-1 rounded-md bg-zinc-200 hover:bg-zinc-300",
                      type: "submit",
                      value: "Comment"
                    })));
}

var CommentInput = {
  make: Jargon$CommentInput
};

function Jargon(Props) {
  var id = Props.id;
  var firestore = Reactfire.useFirestore();
  var jargonDoc = Firestore.doc(firestore, "jargons/" + id + "");
  var match = Reactfire.useFirestoreDocData(jargonDoc);
  var match$1 = match.data;
  var commentsCollection = Firestore.collection(firestore, "jargons/" + id + "/comments");
  var match$2 = Reactfire.useFirestoreCollectionData(Firestore.query(commentsCollection, Firestore.orderBy("timestamp", "asc")), {
        idField: "id"
      });
  if (match.status === "loading" || match$2.status === "loading") {
    return React.createElement("div", {
                className: "h-screen grid justify-center content-center"
              }, React.createElement(Loader.make, {}));
  }
  var match$3 = constructForest(match$2.data);
  return React.createElement("main", {
              className: "grid p-5 gap-3 dark:text-white"
            }, React.createElement("h1", {
                  className: "grid gap-1"
                }, React.createElement("div", {
                      className: "text-3xl font-bold"
                    }, match$1.english), React.createElement("div", {
                      className: "text-2xl font-medium"
                    }, match$1.korean)), React.createElement(Jargon$CommentInput, {}), React.createElement("div", undefined, makeSiblings(match$3[0].contents)));
}

var make = Jargon;

export {
  constructForest ,
  makeComment ,
  makeSiblings ,
  CommentInput ,
  make ,
}
/* react Not a pure module */
