// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "@rescript/react/src/React.js";

var make = React.lazy_(function () {
      return import("./SignIn.js").then(function (m) {
                  return m.make;
                });
    });

var SignIn = {
  make: make
};

var make$1 = React.lazy_(function () {
      return import("./SignOut.js").then(function (m) {
                  return m.make;
                });
    });

var SignOut = {
  make: make$1
};

var make$2 = React.lazy_(function () {
      return import("./Profile.js").then(function (m) {
                  return m.make;
                });
    });

var Profile = {
  make: make$2
};

var make$3 = React.lazy_(function () {
      return import("./NewJargon.js").then(function (m) {
                  return m.make;
                });
    });

var NewJargon = {
  make: make$3
};

var make$4 = React.lazy_(function () {
      return import("./NewTranslation.js").then(function (m) {
                  return m.make;
                });
    });

var NewTranslation = {
  make: make$4
};

var make$5 = React.lazy_(function () {
      return import("./JargonPost.js").then(function (m) {
                  return m.make;
                });
    });

var JargonPost = {
  make: make$5
};

var make$6 = React.lazy_(function () {
      return import("./Why.js").then(function (m) {
                  return m.make;
                });
    });

var Why = {
  make: make$6
};

var make$7 = React.lazy_(function () {
      return import("./Colophon.js").then(function (m) {
                  return m.make;
                });
    });

var Colophon = {
  make: make$7
};

export {
  SignIn ,
  SignOut ,
  Profile ,
  NewJargon ,
  NewTranslation ,
  JargonPost ,
  Why ,
  Colophon ,
}
/* make Not a pure module */
