// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function MultiValueLabel(props) {
  var acronym = props.children.split(" ")[0];
  return JsxRuntime.jsx("div", {
              children: acronym,
              className: "badge badge-md ml-1"
            });
}

var make = MultiValueLabel;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
