// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptReactRouter from "../node_modules/@rescript/react/src/RescriptReactRouter.js";
import * as Solid from "@heroicons/react/24/solid";
import * as Outline from "@heroicons/react/24/outline";

function Navbar(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("label", {
                                      children: JsxRuntime.jsx(Solid.Bars3Icon, {
                                            className: "h-5 w-5"
                                          }),
                                      className: "btn btn-ghost lg:hidden",
                                      tabIndex: 0
                                    }),
                                JsxRuntime.jsxs("ul", {
                                      children: [
                                        JsxRuntime.jsx("li", {
                                              children: JsxRuntime.jsx("button", {
                                                    children: "홈",
                                                    onClick: (function (param) {
                                                        RescriptReactRouter.replace("/");
                                                      })
                                                  })
                                            }),
                                        JsxRuntime.jsx("li", {
                                              children: JsxRuntime.jsx("button", {
                                                    children: "번역 제안",
                                                    onClick: (function (param) {
                                                        RescriptReactRouter.replace("/new-jargon");
                                                      })
                                                  })
                                            })
                                      ],
                                      className: "menu menu-compact dropdown-content mt-3 p-2 shadow bg-base-100 rounded-box w-52",
                                      tabIndex: 0
                                    })
                              ],
                              className: "dropdown"
                            }),
                        JsxRuntime.jsx("button", {
                              children: "EKO: 쉬운 우리말 번역",
                              className: "btn btn-ghost normal-case text-xl",
                              onClick: (function (param) {
                                  RescriptReactRouter.replace("/");
                                })
                            })
                      ],
                      className: "navbar-start"
                    }),
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsxs("ul", {
                            children: [
                              JsxRuntime.jsx("li", {
                                    children: JsxRuntime.jsx("button", {
                                          children: "홈",
                                          onClick: (function (param) {
                                              RescriptReactRouter.replace("/");
                                            })
                                        })
                                  }),
                              JsxRuntime.jsx("li", {
                                    children: JsxRuntime.jsx("button", {
                                          children: "번역 제안",
                                          onClick: (function (param) {
                                              RescriptReactRouter.replace("/new-jargon");
                                            })
                                        })
                                  })
                            ],
                            className: "menu menu-horizontal px-1"
                          }),
                      className: "navbar-center hidden lg:flex"
                    }),
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx("label", {
                                    children: JsxRuntime.jsx(Outline.UserCircleIcon, {
                                          className: "h-6 w-6"
                                        }),
                                    className: "btn btn-circle btn-ghost",
                                    tabIndex: 0
                                  }),
                              JsxRuntime.jsx("ul", {
                                    children: props.signedIn ? JsxRuntime.jsxs(JsxRuntime.Fragment, {
                                            children: [
                                              JsxRuntime.jsx("li", {
                                                    children: JsxRuntime.jsx("button", {
                                                          children: "내 프로필",
                                                          onClick: (function (param) {
                                                              RescriptReactRouter.replace("/profile");
                                                            })
                                                        })
                                                  }),
                                              JsxRuntime.jsx("li", {
                                                    children: JsxRuntime.jsx("button", {
                                                          children: "로그아웃",
                                                          onClick: (function (param) {
                                                              RescriptReactRouter.replace("/logout");
                                                            })
                                                        })
                                                  })
                                            ]
                                          }) : JsxRuntime.jsx("li", {
                                            children: JsxRuntime.jsx("button", {
                                                  children: "로그인",
                                                  onClick: (function (param) {
                                                      RescriptReactRouter.replace("/login");
                                                    })
                                                })
                                          }),
                                    className: "menu menu-compact dropdown-content mt-3 p-2 shadow bg-base-100 rounded-box w-52",
                                    tabIndex: 0
                                  })
                            ],
                            className: "dropdown dropdown-end"
                          }),
                      className: "navbar-end"
                    })
              ],
              className: "navbar bg-base-100"
            });
}

var make = Navbar;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
