// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Reactfire from "reactfire";
import * as SignInContext from "./SignInContext.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as Firestore from "firebase/firestore";
import * as RescriptReactRouter from "../node_modules/@rescript/react/src/RescriptReactRouter.js";
import * as Solid from "@heroicons/react/24/solid";
import * as Outline from "@heroicons/react/24/outline";

function Navbar(props) {
  var match = React.useContext(SignInContext.context);
  var user = match.user;
  var photoURL = !(user == null) ? user.photoURL : undefined;
  var match$1 = React.useState(function () {
        
      });
  var setJargonsCount = match$1[1];
  var jargonsCount = match$1[0];
  var firestore = Reactfire.useFirestore();
  var jargonsCollection = Firestore.collection(firestore, "jargons");
  React.useEffect((function () {
          var countJargons = async function (param) {
            var snapshot = await Firestore.getCountFromServer(jargonsCollection);
            var count = snapshot.data().count;
            return setJargonsCount(function (param) {
                        return count;
                      });
          };
          countJargons();
        }), []);
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("label", {
                                      children: JsxRuntime.jsx(Solid.Bars3Icon, {
                                            className: "h-5 w-5"
                                          }),
                                      className: "btn btn-ghost md:hidden",
                                      tabIndex: 0
                                    }),
                                JsxRuntime.jsxs("ul", {
                                      children: [
                                        JsxRuntime.jsx("li", {
                                              children: JsxRuntime.jsxs("button", {
                                                    children: [
                                                      JsxRuntime.jsx(Solid.StarIcon, {
                                                            className: "h-4 w-4"
                                                          }),
                                                      "배경/원칙"
                                                    ],
                                                    onClick: (function (param) {
                                                        RescriptReactRouter.push("/why");
                                                      })
                                                  })
                                            }),
                                        JsxRuntime.jsx("li", {
                                              children: JsxRuntime.jsxs("button", {
                                                    children: [
                                                      JsxRuntime.jsx(Outline.PencilSquareIcon, {
                                                            className: "h-4 w-4"
                                                          }),
                                                      "용어제안"
                                                    ],
                                                    onClick: (function (param) {
                                                        RescriptReactRouter.push("/new-jargon");
                                                      })
                                                  })
                                            }),
                                        JsxRuntime.jsx("li", {
                                              children: JsxRuntime.jsxs("button", {
                                                    children: [
                                                      JsxRuntime.jsx(Outline.WrenchIcon, {
                                                            className: "h-4 w-4"
                                                          }),
                                                      "제작기"
                                                    ],
                                                    onClick: (function (param) {
                                                        RescriptReactRouter.push("/colophon");
                                                      })
                                                  })
                                            })
                                      ],
                                      className: "menu menu-compact dropdown-content p-2 w-[9rem] shadow bg-teal-50 dark:bg-zinc-800 rounded-box",
                                      tabIndex: 0
                                    })
                              ],
                              className: "dropdown dropdown-hover"
                            }),
                        JsxRuntime.jsx("button", {
                              children: JsxRuntime.jsxs("div", {
                                    children: [
                                      JsxRuntime.jsx("span", {
                                            children: "쉬운 전문용어 𝛼"
                                          }),
                                      JsxRuntime.jsx("span", {
                                            children: "컴퓨터과학/컴퓨터공학",
                                            className: "text-xs"
                                          })
                                    ],
                                    className: "flex items-baseline gap-1"
                                  }),
                              className: "btn btn-ghost text-xl lg:hidden",
                              onClick: (function (param) {
                                  RescriptReactRouter.push("/");
                                })
                            }),
                        JsxRuntime.jsx("button", {
                              children: JsxRuntime.jsxs("div", {
                                    children: [
                                      JsxRuntime.jsx("span", {
                                            children: "쉬운 전문용어 𝛼"
                                          }),
                                      JsxRuntime.jsx("span", {
                                            children: "컴퓨터과학/컴퓨터공학",
                                            className: "text-xs"
                                          })
                                    ],
                                    className: "flex items-baseline gap-1"
                                  }),
                              className: "btn btn-ghost text-xl hidden lg:flex",
                              onClick: (function (param) {
                                  RescriptReactRouter.push("/");
                                })
                            })
                      ],
                      className: "navbar-start"
                    }),
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsxs("ul", {
                            children: [
                              JsxRuntime.jsx("li", {
                                    children: JsxRuntime.jsx("button", {
                                          children: JsxRuntime.jsxs("div", {
                                                children: [
                                                  JsxRuntime.jsx(Solid.StarIcon, {
                                                        className: "h-6 w-6 hidden sm:flex"
                                                      }),
                                                  "배경/원칙"
                                                ],
                                                className: "grid justify-items-center"
                                              }),
                                          onClick: (function (param) {
                                              RescriptReactRouter.push("/why");
                                            })
                                        })
                                  }),
                              JsxRuntime.jsx("li", {
                                    children: JsxRuntime.jsx("button", {
                                          children: JsxRuntime.jsxs("div", {
                                                children: [
                                                  JsxRuntime.jsx(Outline.PencilSquareIcon, {
                                                        className: "h-6 w-6 hidden sm:flex"
                                                      }),
                                                  "용어제안"
                                                ],
                                                className: "grid justify-items-center"
                                              }),
                                          onClick: (function (param) {
                                              RescriptReactRouter.push("/new-jargon");
                                            })
                                        })
                                  }),
                              JsxRuntime.jsx("li", {
                                    children: JsxRuntime.jsx("button", {
                                          children: JsxRuntime.jsxs("div", {
                                                children: [
                                                  JsxRuntime.jsx(Outline.WrenchIcon, {
                                                        className: "h-6 w-6 hidden sm:flex"
                                                      }),
                                                  "제작기"
                                                ],
                                                className: "grid justify-items-center"
                                              }),
                                          onClick: (function (param) {
                                              RescriptReactRouter.push("/colophon");
                                            })
                                        })
                                  })
                            ],
                            className: "menu menu-horizontal px-1"
                          }),
                      className: "navbar-center hidden md:flex text-sm"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        jargonsCount !== undefined ? JsxRuntime.jsxs("div", {
                                children: [
                                  JsxRuntime.jsx(Outline.ChartBarSquareIcon, {
                                        className: "h-5 w-5"
                                      }),
                                  JsxRuntime.jsx("div", {
                                        children: "총 " + String(jargonsCount) + "개",
                                        className: "ml-0"
                                      })
                                ],
                                className: "items-center sm:gap-1 text-xs text-teal-800 hidden sm:flex"
                              }) : null,
                        JsxRuntime.jsxs("div", {
                              children: [
                                photoURL !== undefined ? JsxRuntime.jsx("img", {
                                        className: "mask mask-squircle h-8 w-8 m-2 cursor-pointer",
                                        tabIndex: 0,
                                        src: photoURL
                                      }) : JsxRuntime.jsx("label", {
                                        children: JsxRuntime.jsx(Outline.UserCircleIcon, {
                                              className: "h-6 w-6"
                                            }),
                                        className: "btn btn-circle btn-ghost",
                                        tabIndex: 0
                                      }),
                                JsxRuntime.jsx("ul", {
                                      children: match.signedIn ? JsxRuntime.jsxs(JsxRuntime.Fragment, {
                                              children: [
                                                JsxRuntime.jsx("li", {
                                                      children: JsxRuntime.jsx("button", {
                                                            children: "내 프로필",
                                                            onClick: (function (param) {
                                                                RescriptReactRouter.push("/profile");
                                                              })
                                                          })
                                                    }),
                                                JsxRuntime.jsx("li", {
                                                      children: JsxRuntime.jsx("button", {
                                                            children: "로그아웃",
                                                            onClick: (function (param) {
                                                                RescriptReactRouter.push("/logout");
                                                              })
                                                          })
                                                    })
                                              ]
                                            }) : JsxRuntime.jsx("li", {
                                              children: JsxRuntime.jsx("button", {
                                                    children: "로그인",
                                                    onClick: (function (param) {
                                                        RescriptReactRouter.push("/login");
                                                      })
                                                  })
                                            }),
                                      className: "menu menu-compact dropdown-content p-2 w-[6.5rem] shadow bg-teal-50 dark:bg-zinc-800 rounded-box",
                                      tabIndex: 0
                                    })
                              ],
                              className: "dropdown dropdown-hover dropdown-end"
                            })
                      ],
                      className: "navbar-end sm:gap-2"
                    })
              ],
              className: "navbar sticky top-0 z-50 bg-base-100"
            });
}

var make = Navbar;

export {
  make ,
}
/* react Not a pure module */
