// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "../node_modules/rescript/lib/es6/curry.js";
import * as React from "react";
import * as Reactfire from "reactfire";
import * as Belt_Option from "../node_modules/rescript/lib/es6/belt_Option.js";
import * as Js_promise2 from "../node_modules/rescript/lib/es6/js_promise2.js";
import * as SignInContext from "./SignInContext.js";
import * as Auth from "firebase/auth";
import * as Client from "@apollo/client";
import * as JsxRuntime from "react/jsx-runtime";
import * as Caml_js_exceptions from "../node_modules/rescript/lib/es6/caml_js_exceptions.js";
import * as Firestore from "firebase/firestore";
import * as RescriptReactRouter from "../node_modules/@rescript/react/src/RescriptReactRouter.js";
import * as ApolloClient__React_Hooks_UseMutation from "../node_modules/rescript-apollo-client/src/@apollo/client/react/hooks/ApolloClient__React_Hooks_UseMutation.js";

var Raw = {};

var query = Client.gql(["mutation ($uid: String!, $displayName: String!)  {\nupdate_user_by_pk(pk_columns: {id: $uid}, _set: {display_name: $displayName})  {\n__typename  \nid  \n}\n\n}\n"]);

function parse(value) {
  var value$1 = value.update_user_by_pk;
  return {
          update_user_by_pk: !(value$1 == null) ? ({
                __typename: value$1.__typename,
                id: value$1.id
              }) : undefined
        };
}

function serialize(value) {
  var value$1 = value.update_user_by_pk;
  var update_user_by_pk;
  if (value$1 !== undefined) {
    var value$2 = value$1.id;
    var value$3 = value$1.__typename;
    update_user_by_pk = {
      __typename: value$3,
      id: value$2
    };
  } else {
    update_user_by_pk = null;
  }
  return {
          update_user_by_pk: update_user_by_pk
        };
}

function serializeVariables(inp) {
  return {
          uid: inp.uid,
          displayName: inp.displayName
        };
}

function makeVariables(uid, displayName, param) {
  return {
          uid: uid,
          displayName: displayName
        };
}

var DisplayNameMutation_inner = {
  Raw: Raw,
  query: query,
  parse: parse,
  serialize: serialize,
  serializeVariables: serializeVariables,
  makeVariables: makeVariables
};

var include = ApolloClient__React_Hooks_UseMutation.Extend({
      query: query,
      Raw: Raw,
      parse: parse,
      serialize: serialize,
      serializeVariables: serializeVariables
    });

var use = include.use;

var DisplayNameMutation_useWithVariables = include.useWithVariables;

var DisplayNameMutation = {
  DisplayNameMutation_inner: DisplayNameMutation_inner,
  Raw: Raw,
  query: query,
  parse: parse,
  serialize: serialize,
  serializeVariables: serializeVariables,
  makeVariables: makeVariables,
  use: use,
  useWithVariables: DisplayNameMutation_useWithVariables
};

function Profile$SignedInProfile(props) {
  var user = props.user;
  var firestore = Reactfire.useFirestore();
  var match = Curry.app(use, [
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined
      ]);
  var mutate = match[0];
  var match$1 = React.useState(function () {
        return Belt_Option.getWithDefault(user.displayName, "");
      });
  var setDisplayName = match$1[1];
  var displayName = match$1[0];
  var handleDisplayNameChange = function ($$event) {
    var value = $$event.currentTarget.value;
    setDisplayName(function (param) {
          return value;
        });
  };
  var match$2 = React.useState(function () {
        return false;
      });
  var setDisabled = match$2[1];
  var handleSubmit = function ($$event) {
    $$event.preventDefault();
    if (displayName.length <= 0) {
      window.alert("필명을 입력해주세요");
    } else {
      setDisabled(function (param) {
            return true;
          });
      ((async function (param) {
              try {
                var authUpdate = Auth.updateProfile(user, {
                      displayName: displayName
                    });
                var docUpdate = (async function (param) {
                      var userDocRef = Firestore.doc(firestore, "users/" + user.uid + "");
                      var userDoc = await Firestore.getDoc(userDocRef);
                      if (userDoc.exists()) {
                        return await Firestore.updateDoc(userDocRef, {
                                    displayName: displayName
                                  });
                      } else {
                        console.warn("User document does not exist!");
                        return await Firestore.setDoc(userDocRef, {
                                    displayName: displayName,
                                    email: user.email
                                  });
                      }
                    })(undefined);
                var dbUpdate = Js_promise2.then(Curry._8(mutate, undefined, undefined, undefined, undefined, undefined, undefined, undefined, {
                          uid: user.uid,
                          displayName: displayName
                        }), (function (param) {
                        return Promise.resolve(undefined);
                      }));
                await Promise.all([
                      authUpdate,
                      docUpdate,
                      dbUpdate
                    ]);
              }
              catch (raw_e){
                var e = Caml_js_exceptions.internalToOCamlException(raw_e);
                console.warn(e);
              }
              return setDisabled(function (param) {
                          return false;
                        });
            })(undefined));
    }
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "내 정보"
                    }),
                JsxRuntime.jsx("form", {
                      children: JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsxs("label", {
                                    children: [
                                      JsxRuntime.jsx("label", {
                                            children: JsxRuntime.jsx("span", {
                                                  children: "필명",
                                                  className: "label-text"
                                                }),
                                            className: "label"
                                          }),
                                      JsxRuntime.jsx("input", {
                                            className: "input input-bordered w-full",
                                            type: "text",
                                            value: displayName,
                                            onChange: handleDisplayNameChange
                                          })
                                    ],
                                    className: "block"
                                  }),
                              JsxRuntime.jsxs("label", {
                                    children: [
                                      JsxRuntime.jsx("label", {
                                            children: JsxRuntime.jsx("span", {
                                                  children: "이메일",
                                                  className: "label-text"
                                                }),
                                            className: "label"
                                          }),
                                      JsxRuntime.jsx("input", {
                                            className: "input input-bordered input-disabled w-full",
                                            readOnly: true,
                                            type: "email",
                                            value: Belt_Option.getWithDefault(user.email, "")
                                          })
                                    ],
                                    className: "block"
                                  }),
                              JsxRuntime.jsx("input", {
                                    className: "btn btn-primary",
                                    disabled: match$2[0],
                                    type: "submit",
                                    value: "저장"
                                  })
                            ],
                            className: "grid grid-cols-1 gap-6"
                          }),
                      className: "mt-8 max-w-md",
                      onSubmit: handleSubmit
                    })
              ],
              className: "px-6 py-12 max-w-xl mx-auto md:max-w-4xl prose"
            });
}

var SignedInProfile = {
  make: Profile$SignedInProfile
};

function Profile(props) {
  var match = React.useContext(SignInContext.context);
  var user = match.user;
  if (match.signedIn && !(user == null)) {
    return JsxRuntime.jsx(Profile$SignedInProfile, {
                user: user
              });
  } else {
    RescriptReactRouter.replace("/login");
    return null;
  }
}

var make = Profile;

export {
  DisplayNameMutation ,
  SignedInProfile ,
  make ,
}
/* query Not a pure module */
