// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Util from "./Util.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.js";
import * as RescriptRelay_Fragment from "rescript-relay/src/RescriptRelay_Fragment.js";
import * as RelatedJargons_jargon_graphql from "./__generated__/RelatedJargons_jargon_graphql.js";

var convertFragment = RelatedJargons_jargon_graphql.Internal.convertFragment;

function waitForFragmentData(environment, fRef) {
  return RescriptRelay_Fragment.waitForFragmentData(environment, RelatedJargons_jargon_graphql.node, convertFragment, fRef);
}

function use(fRef) {
  return RescriptRelay_Fragment.useFragment(RelatedJargons_jargon_graphql.node, convertFragment, fRef);
}

function useOpt(fRef) {
  return RescriptRelay_Fragment.useFragmentOpt(fRef !== undefined ? Caml_option.some(Caml_option.valFromOption(fRef)) : undefined, RelatedJargons_jargon_graphql.node, convertFragment);
}

function readResolverFragment(fRef) {
  return RescriptRelay_Fragment.read(RelatedJargons_jargon_graphql.node, convertFragment, fRef);
}

var RelatedJargonsFragment = {
  Types: undefined,
  Operation: undefined,
  convertFragment: convertFragment,
  waitForFragmentData: waitForFragmentData,
  use: use,
  useOpt: useOpt,
  readResolverFragment: readResolverFragment
};

function RelatedJargons(props) {
  var match = use(props.relatedJargonsRef);
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("div", {
                      children: "연관 용어",
                      className: "font-medium"
                    }),
                JsxRuntime.jsx("div", {
                      children: match.related_jargons.map(function (r) {
                            return Util.badgify((function (param) {
                                          RescriptReactRouter.push("/jargon/" + r.jargon.id);
                                        }), r.jargon.name);
                          }),
                      className: "flex gap-1"
                    })
              ],
              className: "flex gap-2"
            });
}

var make = RelatedJargons;

export {
  RelatedJargonsFragment ,
  make ,
}
/* Util Not a pure module */
