// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Loader from "./Loader.js";
import * as Firebase from "./Firebase.js";
import * as Reactfire from "reactfire";
import * as Auth from "firebase/auth";
import * as ReactFirebaseui from "react-firebaseui";
import App from "firebase/compat/app";

var uiConfig = {
  signInFlow: "popup",
  signInOptions: [
    Firebase.Auth.EmailAuthProvider.providerID,
    Firebase.Auth.GithubAuthProvider.providerID
  ],
  callbacks: {
    signInSuccessWithAuthResult: (function (param) {
        return false;
      })
  }
};

function SignIn(Props) {
  var match = Reactfire.useSigninCheck();
  var app = App.initializeApp(Reactfire.useAuth().app.options);
  var firebaseAuth = Auth.getAuth(app);
  if (match.status === "loading") {
    return React.createElement("div", {
                className: "h-screen grid justify-center content-center"
              }, React.createElement(Loader.make, {}));
  } else {
    return React.createElement("div", {
                className: "h-screen grid justify-center content-center dark:text-white"
              }, match.data.signedIn ? "Already signed in!" : React.createElement(ReactFirebaseui.StyledFirebaseAuth, {
                      uiConfig: uiConfig,
                      firebaseAuth: firebaseAuth
                    }));
  }
}

var make = SignIn;

export {
  uiConfig ,
  make ,
}
/* react Not a pure module */
