// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

var context = React.createContext({
      signedIn: false,
      user: undefined
    });

var make = context.Provider;

var Provider = {
  make: make
};

export {
  context ,
  Provider ,
}
/* context Not a pure module */
