// Generated by ReScript, PLEASE EDIT WITH CARE


function getCode(c) {
  return c.charCodeAt(0) | 0;
}

function endsWithJong(korean) {
  var c = korean.charAt(korean.length - 1 | 0);
  if ("가" <= c && c <= "힣") {
    return ((c.charCodeAt(0) | 0) - ("가".charCodeAt(0) | 0) | 0) % 28 > 0;
  } else {
    return false;
  }
}

function eulLeul(korean) {
  return korean + (
          endsWithJong(korean) ? "을" : "를"
        );
}

export {
  getCode ,
  endsWithJong ,
  eulLeul ,
}
/* No side effect */
