// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function getCode(c) {
  return c.charCodeAt(0) | 0;
}

function endsWithJong(korean) {
  var c = korean.charAt(korean.length - 1 | 0);
  if ("가" <= c && c <= "힣") {
    return ((c.charCodeAt(0) | 0) - ("가".charCodeAt(0) | 0) | 0) % 28 > 0;
  } else {
    return false;
  }
}

function eulLeul(korean) {
  return korean + (
          endsWithJong(korean) ? "을" : "를"
        );
}

function useDebounce(value, delay) {
  var match = React.useState(function () {
        return value;
      });
  var setDebouncedValue = match[1];
  React.useEffect((function () {
          var handler = setTimeout((function () {
                  setDebouncedValue(function (param) {
                        return value;
                      });
                }), delay);
          return (function () {
                    clearTimeout(handler);
                  });
        }), [
        value,
        delay
      ]);
  return match[0];
}

export {
  getCode ,
  endsWithJong ,
  eulLeul ,
  useDebounce ,
}
/* react Not a pure module */
